import json
import yaml
import requests

def json_to_yaml(url, yaml_file):
	with open(yaml_file, 'w') as f:
		# Write a comment at the beginning of the YAML file
		f.write("# This file is automatically generated from {}\n".format(url))
		f.write("# Any manual changes will be overwritten during the next build!\n\n")

		response = requests.get(url)
		data = response.json().get('data')

		# Process each video item in the data
		for item in data:
				# Remove some keys (and their content) to reduce the yml file size
				item.pop('account', None)
				item.pop('channel', None)
				item.pop('language', None)
				item.pop('licence', None)
				item.pop('category', None)
				item.pop('aspectRatio', None)
				item.pop('dislikes', None)

				# Check if 'originallyPublishedAt' is null and replace it with 'publishedAt' if so
      	# (this is because videos were re-uploaded, and some of the new ones don't have 'originallyPublishedAt.')
				if item.get('originallyPublishedAt') is None:
						item['originallyPublishedAt'] = item.get('publishedAt')

		yaml.dump(data, f, default_flow_style=False)

# Fetch data from the sources and output
json_to_yaml('https://techlore.tv/api/v1/video-channels/techlore/videos?count=100&sort=-originallyPublishedAt', '_data/_en/forum/latest-techlore-videos.yml')
json_to_yaml('https://apertatube.net/api/v1/video-channels/surveillancereport/videos?count=2&sort=-publishedAt', '_data/_en/forum/latest-surveillance-report-videos.yml')
json_to_yaml('https://techlore.tv/api/v1/video-channels/techlore_clips/videos?count=100&sort=-originallyPublishedAt', '_data/_en/forum/latest-techlore-clips-videos.yml')
