import json
import yaml
import requests

def json_to_yaml(url, yaml_file):
    response = requests.get(url)
    data = response.json().get('topic_list').get('topics')

		# Write a comment at the beginning of the YAML file
    with open(yaml_file, 'w') as f:
        f.write("# This file is automatically generated from {}\n".format(url))
        f.write("# Any manual changes will be overwritten during the next build!\n\n")
        yaml.dump(data, f, default_flow_style=False)

# Example usage
json_to_yaml('https://discuss.techlore.tech/c/content/techlore/20.json?order=created', '_data/_en/forum/latest-techlore-videos.yml')
json_to_yaml('https://discuss.techlore.tech/c/content/surveillance-report/21.json?order=created', '_data/_en/forum/latest-surveillance-report-videos.yml')
json_to_yaml('https://discuss.techlore.tech/c/content/techlore-clips/19.json?order=created', '_data/_en/forum/latest-techlore-clips-videos.yml')
